# Generated by Django 4.0.6 on 2023-03-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='image',
            field=models.ImageField(blank=True, default='profiles/default.jpeg', null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profiles/default.jpeg', null=True, upload_to='profiles/'),
        ),
    ]
