# Generated by Django 4.0.6 on 2023-02-14 09:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='classes/default.png', null=True, upload_to='classes/')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staffprofile')),
                ('users', models.ManyToManyField(to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('no', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('class_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('value', models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent')], max_length=10, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('class_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.lecture')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
